// Generated by scripts/extract-formations.mjs from the official rulebook pp. 18-27.
// Do not edit by hand; re-run the extractor instead.
import type { Coord, Ship } from '$lib/engine/types';

export interface Formation {
	ships: Ship[];
	/** Deck cells the two aircraft occupy. */
	aircraft: Coord[];
}

export type FormationId = keyof typeof FORMATIONS;

export const FORMATIONS = {
	A1: {
		ships: [
			{ class: 'CV', bow: { row: 6, col: 6 }, facing: 'W' },
			{ class: 'BB', bow: { row: 4, col: 9 }, facing: 'W' },
			{ class: 'DD', bow: { row: 8, col: 1 }, facing: 'W' },
			{ class: 'DE', bow: { row: 1, col: 3 }, facing: 'W' },
			{ class: 'PB', bow: { row: 6, col: 13 }, facing: 'N' }
		],
		aircraft: [{ row: 6, col: 7 }, { row: 6, col: 9 }]
	},
	A2: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 0 }, facing: 'N' },
			{ class: 'BB', bow: { row: 1, col: 4 }, facing: 'N' },
			{ class: 'DD', bow: { row: 5, col: 13 }, facing: 'N' },
			{ class: 'DE', bow: { row: 9, col: 5 }, facing: 'W' },
			{ class: 'PB', bow: { row: 6, col: 10 }, facing: 'E' }
		],
		aircraft: [{ row: 1, col: 0 }, { row: 5, col: 0 }]
	},
	A3: {
		ships: [
			{ class: 'CV', bow: { row: 2, col: 8 }, facing: 'N' },
			{ class: 'BB', bow: { row: 2, col: 12 }, facing: 'N' },
			{ class: 'DD', bow: { row: 0, col: 0 }, facing: 'N' },
			{ class: 'DE', bow: { row: 0, col: 4 }, facing: 'W' },
			{ class: 'PB', bow: { row: 5, col: 0 }, facing: 'S' }
		],
		aircraft: [{ row: 4, col: 8 }, { row: 5, col: 8 }]
	},
	A4: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 6 }, facing: 'E' },
			{ class: 'BB', bow: { row: 5, col: 6 }, facing: 'E' },
			{ class: 'DD', bow: { row: 8, col: 8 }, facing: 'S' },
			{ class: 'DE', bow: { row: 7, col: 3 }, facing: 'N' },
			{ class: 'PB', bow: { row: 7, col: 2 }, facing: 'S' }
		],
		aircraft: [{ row: 3, col: 3 }, { row: 3, col: 4 }]
	},
	A5: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 6 }, facing: 'W' },
			{ class: 'BB', bow: { row: 3, col: 5 }, facing: 'W' },
			{ class: 'DD', bow: { row: 9, col: 3 }, facing: 'S' },
			{ class: 'DE', bow: { row: 3, col: 10 }, facing: 'W' },
			{ class: 'PB', bow: { row: 8, col: 8 }, facing: 'N' }
		],
		aircraft: [{ row: 1, col: 9 }, { row: 1, col: 10 }]
	},
	A6: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 10 }, facing: 'E' },
			{ class: 'BB', bow: { row: 7, col: 12 }, facing: 'S' },
			{ class: 'DD', bow: { row: 0, col: 7 }, facing: 'N' },
			{ class: 'DE', bow: { row: 7, col: 2 }, facing: 'W' },
			{ class: 'PB', bow: { row: 9, col: 11 }, facing: 'W' }
		],
		aircraft: [{ row: 4, col: 6 }, { row: 4, col: 7 }]
	},
	A7: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 8 }, facing: 'E' },
			{ class: 'BB', bow: { row: 8, col: 10 }, facing: 'S' },
			{ class: 'DD', bow: { row: 3, col: 8 }, facing: 'W' },
			{ class: 'DE', bow: { row: 1, col: 7 }, facing: 'N' },
			{ class: 'PB', bow: { row: 6, col: 13 }, facing: 'N' }
		],
		aircraft: [{ row: 9, col: 4 }, { row: 9, col: 6 }]
	},
	A8: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 5 }, facing: 'E' },
			{ class: 'BB', bow: { row: 2, col: 10 }, facing: 'W' },
			{ class: 'DD', bow: { row: 7, col: 5 }, facing: 'W' },
			{ class: 'DE', bow: { row: 4, col: 1 }, facing: 'W' },
			{ class: 'PB', bow: { row: 8, col: 8 }, facing: 'E' }
		],
		aircraft: [{ row: 9, col: 1 }, { row: 9, col: 4 }]
	},
	A9: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 2 }, facing: 'S' },
			{ class: 'BB', bow: { row: 6, col: 2 }, facing: 'W' },
			{ class: 'DD', bow: { row: 4, col: 0 }, facing: 'N' },
			{ class: 'DE', bow: { row: 1, col: 11 }, facing: 'W' },
			{ class: 'PB', bow: { row: 6, col: 7 }, facing: 'S' }
		],
		aircraft: [{ row: 1, col: 2 }, { row: 4, col: 2 }]
	},
	A10: {
		ships: [
			{ class: 'CV', bow: { row: 6, col: 3 }, facing: 'W' },
			{ class: 'BB', bow: { row: 1, col: 8 }, facing: 'N' },
			{ class: 'DD', bow: { row: 3, col: 11 }, facing: 'W' },
			{ class: 'DE', bow: { row: 2, col: 0 }, facing: 'N' },
			{ class: 'PB', bow: { row: 8, col: 10 }, facing: 'N' }
		],
		aircraft: [{ row: 6, col: 5 }, { row: 6, col: 7 }]
	},
	B1: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 6 }, facing: 'W' },
			{ class: 'BB', bow: { row: 9, col: 3 }, facing: 'W' },
			{ class: 'DD', bow: { row: 6, col: 9 }, facing: 'N' },
			{ class: 'DE', bow: { row: 7, col: 6 }, facing: 'W' },
			{ class: 'PB', bow: { row: 1, col: 1 }, facing: 'N' }
		],
		aircraft: [{ row: 4, col: 7 }, { row: 4, col: 9 }]
	},
	B2: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 4 }, facing: 'S' },
			{ class: 'BB', bow: { row: 1, col: 6 }, facing: 'N' },
			{ class: 'DD', bow: { row: 5, col: 12 }, facing: 'S' },
			{ class: 'DE', bow: { row: 5, col: 0 }, facing: 'W' },
			{ class: 'PB', bow: { row: 7, col: 12 }, facing: 'N' }
		],
		aircraft: [{ row: 3, col: 4 }, { row: 7, col: 4 }]
	},
	B3: {
		ships: [
			{ class: 'CV', bow: { row: 2, col: 3 }, facing: 'W' },
			{ class: 'BB', bow: { row: 8, col: 9 }, facing: 'S' },
			{ class: 'DD', bow: { row: 9, col: 11 }, facing: 'W' },
			{ class: 'DE', bow: { row: 2, col: 13 }, facing: 'N' },
			{ class: 'PB', bow: { row: 5, col: 12 }, facing: 'N' }
		],
		aircraft: [{ row: 2, col: 5 }, { row: 2, col: 6 }]
	},
	B4: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 8 }, facing: 'W' },
			{ class: 'BB', bow: { row: 2, col: 2 }, facing: 'W' },
			{ class: 'DD', bow: { row: 4, col: 1 }, facing: 'W' },
			{ class: 'DE', bow: { row: 1, col: 12 }, facing: 'N' },
			{ class: 'PB', bow: { row: 5, col: 8 }, facing: 'N' }
		],
		aircraft: [{ row: 8, col: 9 }, { row: 8, col: 10 }]
	},
	B5: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 9 }, facing: 'S' },
			{ class: 'BB', bow: { row: 5, col: 12 }, facing: 'N' },
			{ class: 'DD', bow: { row: 6, col: 5 }, facing: 'W' },
			{ class: 'DE', bow: { row: 0, col: 10 }, facing: 'N' },
			{ class: 'PB', bow: { row: 0, col: 5 }, facing: 'W' }
		],
		aircraft: [{ row: 7, col: 9 }, { row: 8, col: 9 }]
	},
	B6: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 1 }, facing: 'S' },
			{ class: 'BB', bow: { row: 0, col: 13 }, facing: 'N' },
			{ class: 'DD', bow: { row: 8, col: 6 }, facing: 'W' },
			{ class: 'DE', bow: { row: 6, col: 13 }, facing: 'E' },
			{ class: 'PB', bow: { row: 2, col: 6 }, facing: 'S' }
		],
		aircraft: [{ row: 0, col: 1 }, { row: 1, col: 1 }]
	},
	B7: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 13 }, facing: 'N' },
			{ class: 'BB', bow: { row: 0, col: 4 }, facing: 'W' },
			{ class: 'DD', bow: { row: 7, col: 4 }, facing: 'W' },
			{ class: 'DE', bow: { row: 1, col: 8 }, facing: 'N' },
			{ class: 'PB', bow: { row: 5, col: 4 }, facing: 'S' }
		],
		aircraft: [{ row: 3, col: 13 }, { row: 5, col: 13 }]
	},
	B8: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 13 }, facing: 'N' },
			{ class: 'BB', bow: { row: 5, col: 8 }, facing: 'W' },
			{ class: 'DD', bow: { row: 7, col: 5 }, facing: 'W' },
			{ class: 'DE', bow: { row: 8, col: 7 }, facing: 'W' },
			{ class: 'PB', bow: { row: 7, col: 1 }, facing: 'E' }
		],
		aircraft: [{ row: 1, col: 13 }, { row: 4, col: 13 }]
	},
	B9: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 13 }, facing: 'N' },
			{ class: 'BB', bow: { row: 0, col: 7 }, facing: 'W' },
			{ class: 'DD', bow: { row: 7, col: 4 }, facing: 'W' },
			{ class: 'DE', bow: { row: 4, col: 6 }, facing: 'S' },
			{ class: 'PB', bow: { row: 5, col: 4 }, facing: 'S' }
		],
		aircraft: [{ row: 4, col: 13 }, { row: 7, col: 13 }]
	},
	B10: {
		ships: [
			{ class: 'CV', bow: { row: 6, col: 3 }, facing: 'S' },
			{ class: 'BB', bow: { row: 8, col: 4 }, facing: 'W' },
			{ class: 'DD', bow: { row: 4, col: 0 }, facing: 'N' },
			{ class: 'DE', bow: { row: 0, col: 3 }, facing: 'E' },
			{ class: 'PB', bow: { row: 2, col: 12 }, facing: 'W' }
		],
		aircraft: [{ row: 4, col: 3 }, { row: 6, col: 3 }]
	},
	C1: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 4 }, facing: 'W' },
			{ class: 'BB', bow: { row: 1, col: 8 }, facing: 'N' },
			{ class: 'DD', bow: { row: 0, col: 10 }, facing: 'W' },
			{ class: 'DE', bow: { row: 3, col: 10 }, facing: 'S' },
			{ class: 'PB', bow: { row: 4, col: 6 }, facing: 'S' }
		],
		aircraft: [{ row: 7, col: 5 }, { row: 7, col: 7 }]
	},
	C2: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 13 }, facing: 'S' },
			{ class: 'BB', bow: { row: 6, col: 1 }, facing: 'N' },
			{ class: 'DD', bow: { row: 7, col: 7 }, facing: 'W' },
			{ class: 'DE', bow: { row: 5, col: 3 }, facing: 'S' },
			{ class: 'PB', bow: { row: 4, col: 6 }, facing: 'E' }
		],
		aircraft: [{ row: 3, col: 13 }, { row: 7, col: 13 }]
	},
	C3: {
		ships: [
			{ class: 'CV', bow: { row: 2, col: 13 }, facing: 'N' },
			{ class: 'BB', bow: { row: 9, col: 0 }, facing: 'S' },
			{ class: 'DD', bow: { row: 4, col: 3 }, facing: 'W' },
			{ class: 'DE', bow: { row: 8, col: 3 }, facing: 'S' },
			{ class: 'PB', bow: { row: 3, col: 11 }, facing: 'N' }
		],
		aircraft: [{ row: 4, col: 13 }, { row: 5, col: 13 }]
	},
	C4: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 5 }, facing: 'W' },
			{ class: 'BB', bow: { row: 5, col: 3 }, facing: 'N' },
			{ class: 'DD', bow: { row: 7, col: 6 }, facing: 'N' },
			{ class: 'DE', bow: { row: 4, col: 5 }, facing: 'W' },
			{ class: 'PB', bow: { row: 7, col: 13 }, facing: 'N' }
		],
		aircraft: [{ row: 1, col: 6 }, { row: 1, col: 7 }]
	},
	C5: {
		ships: [
			{ class: 'CV', bow: { row: 0, col: 2 }, facing: 'N' },
			{ class: 'BB', bow: { row: 6, col: 6 }, facing: 'E' },
			{ class: 'DD', bow: { row: 9, col: 13 }, facing: 'S' },
			{ class: 'DE', bow: { row: 9, col: 10 }, facing: 'W' },
			{ class: 'PB', bow: { row: 5, col: 13 }, facing: 'S' }
		],
		aircraft: [{ row: 3, col: 2 }, { row: 4, col: 2 }]
	},
	C6: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 2 }, facing: 'S' },
			{ class: 'BB', bow: { row: 8, col: 12 }, facing: 'S' },
			{ class: 'DD', bow: { row: 1, col: 4 }, facing: 'N' },
			{ class: 'DE', bow: { row: 6, col: 7 }, facing: 'N' },
			{ class: 'PB', bow: { row: 4, col: 7 }, facing: 'E' }
		],
		aircraft: [{ row: 3, col: 2 }, { row: 4, col: 2 }]
	},
	C7: {
		ships: [
			{ class: 'CV', bow: { row: 6, col: 2 }, facing: 'W' },
			{ class: 'BB', bow: { row: 4, col: 0 }, facing: 'W' },
			{ class: 'DD', bow: { row: 6, col: 0 }, facing: 'N' },
			{ class: 'DE', bow: { row: 4, col: 6 }, facing: 'W' },
			{ class: 'PB', bow: { row: 3, col: 8 }, facing: 'W' }
		],
		aircraft: [{ row: 6, col: 2 }, { row: 6, col: 4 }]
	},
	C8: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 12 }, facing: 'N' },
			{ class: 'BB', bow: { row: 3, col: 3 }, facing: 'N' },
			{ class: 'DD', bow: { row: 1, col: 7 }, facing: 'N' },
			{ class: 'DE', bow: { row: 9, col: 8 }, facing: 'E' },
			{ class: 'PB', bow: { row: 3, col: 0 }, facing: 'S' }
		],
		aircraft: [{ row: 3, col: 12 }, { row: 6, col: 12 }]
	},
	C9: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 5 }, facing: 'N' },
			{ class: 'BB', bow: { row: 6, col: 10 }, facing: 'N' },
			{ class: 'DD', bow: { row: 2, col: 3 }, facing: 'E' },
			{ class: 'DE', bow: { row: 0, col: 5 }, facing: 'N' },
			{ class: 'PB', bow: { row: 5, col: 12 }, facing: 'N' }
		],
		aircraft: [{ row: 5, col: 5 }, { row: 8, col: 5 }]
	},
	C10: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 6 }, facing: 'E' },
			{ class: 'BB', bow: { row: 6, col: 7 }, facing: 'W' },
			{ class: 'DD', bow: { row: 8, col: 10 }, facing: 'E' },
			{ class: 'DE', bow: { row: 0, col: 1 }, facing: 'N' },
			{ class: 'PB', bow: { row: 3, col: 3 }, facing: 'E' }
		],
		aircraft: [{ row: 1, col: 4 }, { row: 1, col: 6 }]
	},
	D1: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 9 }, facing: 'E' },
			{ class: 'BB', bow: { row: 2, col: 2 }, facing: 'N' },
			{ class: 'DD', bow: { row: 0, col: 11 }, facing: 'W' },
			{ class: 'DE', bow: { row: 5, col: 10 }, facing: 'W' },
			{ class: 'PB', bow: { row: 1, col: 4 }, facing: 'N' }
		],
		aircraft: [{ row: 4, col: 6 }, { row: 4, col: 8 }]
	},
	D2: {
		ships: [
			{ class: 'CV', bow: { row: 0, col: 4 }, facing: 'W' },
			{ class: 'BB', bow: { row: 6, col: 2 }, facing: 'S' },
			{ class: 'DD', bow: { row: 7, col: 10 }, facing: 'N' },
			{ class: 'DE', bow: { row: 5, col: 10 }, facing: 'S' },
			{ class: 'PB', bow: { row: 7, col: 4 }, facing: 'N' }
		],
		aircraft: [{ row: 0, col: 4 }, { row: 0, col: 8 }]
	},
	D3: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 9 }, facing: 'E' },
			{ class: 'BB', bow: { row: 0, col: 0 }, facing: 'W' },
			{ class: 'DD', bow: { row: 4, col: 3 }, facing: 'W' },
			{ class: 'DE', bow: { row: 3, col: 12 }, facing: 'S' },
			{ class: 'PB', bow: { row: 3, col: 0 }, facing: 'N' }
		],
		aircraft: [{ row: 1, col: 7 }, { row: 1, col: 8 }]
	},
	D4: {
		ships: [
			{ class: 'CV', bow: { row: 2, col: 9 }, facing: 'E' },
			{ class: 'BB', bow: { row: 4, col: 0 }, facing: 'W' },
			{ class: 'DD', bow: { row: 9, col: 1 }, facing: 'W' },
			{ class: 'DE', bow: { row: 7, col: 5 }, facing: 'S' },
			{ class: 'PB', bow: { row: 4, col: 8 }, facing: 'E' }
		],
		aircraft: [{ row: 2, col: 6 }, { row: 2, col: 7 }]
	},
	D5: {
		ships: [
			{ class: 'CV', bow: { row: 2, col: 13 }, facing: 'E' },
			{ class: 'BB', bow: { row: 5, col: 8 }, facing: 'E' },
			{ class: 'DD', bow: { row: 4, col: 9 }, facing: 'W' },
			{ class: 'DE', bow: { row: 9, col: 3 }, facing: 'S' },
			{ class: 'PB', bow: { row: 0, col: 12 }, facing: 'E' }
		],
		aircraft: [{ row: 2, col: 12 }, { row: 2, col: 13 }]
	},
	D6: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 7 }, facing: 'S' },
			{ class: 'BB', bow: { row: 2, col: 11 }, facing: 'N' },
			{ class: 'DD', bow: { row: 8, col: 6 }, facing: 'W' },
			{ class: 'DE', bow: { row: 0, col: 0 }, facing: 'W' },
			{ class: 'PB', bow: { row: 4, col: 4 }, facing: 'W' }
		],
		aircraft: [{ row: 0, col: 7 }, { row: 1, col: 7 }]
	},
	D7: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 0 }, facing: 'S' },
			{ class: 'BB', bow: { row: 5, col: 13 }, facing: 'S' },
			{ class: 'DD', bow: { row: 0, col: 3 }, facing: 'W' },
			{ class: 'DE', bow: { row: 9, col: 8 }, facing: 'S' },
			{ class: 'PB', bow: { row: 8, col: 4 }, facing: 'S' }
		],
		aircraft: [{ row: 4, col: 0 }, { row: 6, col: 0 }]
	},
	D8: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 7 }, facing: 'E' },
			{ class: 'BB', bow: { row: 4, col: 9 }, facing: 'S' },
			{ class: 'DD', bow: { row: 3, col: 0 }, facing: 'N' },
			{ class: 'DE', bow: { row: 2, col: 13 }, facing: 'S' },
			{ class: 'PB', bow: { row: 8, col: 12 }, facing: 'N' }
		],
		aircraft: [{ row: 7, col: 3 }, { row: 7, col: 6 }]
	},
	D9: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 5 }, facing: 'E' },
			{ class: 'BB', bow: { row: 2, col: 6 }, facing: 'N' },
			{ class: 'DD', bow: { row: 6, col: 7 }, facing: 'W' },
			{ class: 'DE', bow: { row: 5, col: 4 }, facing: 'S' },
			{ class: 'PB', bow: { row: 2, col: 11 }, facing: 'W' }
		],
		aircraft: [{ row: 9, col: 2 }, { row: 9, col: 5 }]
	},
	D10: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 10 }, facing: 'N' },
			{ class: 'BB', bow: { row: 7, col: 0 }, facing: 'W' },
			{ class: 'DD', bow: { row: 6, col: 6 }, facing: 'N' },
			{ class: 'DE', bow: { row: 5, col: 6 }, facing: 'E' },
			{ class: 'PB', bow: { row: 1, col: 6 }, facing: 'W' }
		],
		aircraft: [{ row: 5, col: 10 }, { row: 7, col: 10 }]
	},
	E1: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 2 }, facing: 'W' },
			{ class: 'BB', bow: { row: 3, col: 12 }, facing: 'N' },
			{ class: 'DD', bow: { row: 7, col: 0 }, facing: 'W' },
			{ class: 'DE', bow: { row: 7, col: 6 }, facing: 'W' },
			{ class: 'PB', bow: { row: 4, col: 3 }, facing: 'N' }
		],
		aircraft: [{ row: 1, col: 3 }, { row: 1, col: 5 }]
	},
	E2: {
		ships: [
			{ class: 'CV', bow: { row: 0, col: 0 }, facing: 'W' },
			{ class: 'BB', bow: { row: 8, col: 6 }, facing: 'S' },
			{ class: 'DD', bow: { row: 8, col: 2 }, facing: 'W' },
			{ class: 'DE', bow: { row: 5, col: 0 }, facing: 'W' },
			{ class: 'PB', bow: { row: 6, col: 3 }, facing: 'E' }
		],
		aircraft: [{ row: 0, col: 0 }, { row: 0, col: 4 }]
	},
	E3: {
		ships: [
			{ class: 'CV', bow: { row: 5, col: 1 }, facing: 'N' },
			{ class: 'BB', bow: { row: 2, col: 13 }, facing: 'E' },
			{ class: 'DD', bow: { row: 7, col: 3 }, facing: 'N' },
			{ class: 'DE', bow: { row: 1, col: 3 }, facing: 'E' },
			{ class: 'PB', bow: { row: 3, col: 0 }, facing: 'W' }
		],
		aircraft: [{ row: 7, col: 1 }, { row: 8, col: 1 }]
	},
	E4: {
		ships: [
			{ class: 'CV', bow: { row: 5, col: 0 }, facing: 'N' },
			{ class: 'BB', bow: { row: 4, col: 4 }, facing: 'W' },
			{ class: 'DD', bow: { row: 9, col: 3 }, facing: 'W' },
			{ class: 'DE', bow: { row: 6, col: 11 }, facing: 'W' },
			{ class: 'PB', bow: { row: 0, col: 4 }, facing: 'N' }
		],
		aircraft: [{ row: 6, col: 0 }, { row: 7, col: 0 }]
	},
	E5: {
		ships: [
			{ class: 'CV', bow: { row: 5, col: 3 }, facing: 'N' },
			{ class: 'BB', bow: { row: 3, col: 2 }, facing: 'W' },
			{ class: 'DD', bow: { row: 0, col: 0 }, facing: 'N' },
			{ class: 'DE', bow: { row: 2, col: 7 }, facing: 'E' },
			{ class: 'PB', bow: { row: 8, col: 6 }, facing: 'E' }
		],
		aircraft: [{ row: 8, col: 3 }, { row: 9, col: 3 }]
	},
	E6: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 10 }, facing: 'E' },
			{ class: 'BB', bow: { row: 7, col: 6 }, facing: 'E' },
			{ class: 'DD', bow: { row: 8, col: 0 }, facing: 'W' },
			{ class: 'DE', bow: { row: 6, col: 0 }, facing: 'W' },
			{ class: 'PB', bow: { row: 9, col: 4 }, facing: 'E' }
		],
		aircraft: [{ row: 3, col: 6 }, { row: 3, col: 7 }]
	},
	E7: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 8 }, facing: 'E' },
			{ class: 'BB', bow: { row: 3, col: 1 }, facing: 'W' },
			{ class: 'DD', bow: { row: 2, col: 5 }, facing: 'S' },
			{ class: 'DE', bow: { row: 6, col: 4 }, facing: 'W' },
			{ class: 'PB', bow: { row: 6, col: 2 }, facing: 'E' }
		],
		aircraft: [{ row: 8, col: 4 }, { row: 8, col: 6 }]
	},
	E8: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 10 }, facing: 'E' },
			{ class: 'BB', bow: { row: 9, col: 4 }, facing: 'W' },
			{ class: 'DD', bow: { row: 3, col: 4 }, facing: 'N' },
			{ class: 'DE', bow: { row: 3, col: 2 }, facing: 'N' },
			{ class: 'PB', bow: { row: 9, col: 9 }, facing: 'E' }
		],
		aircraft: [{ row: 4, col: 6 }, { row: 4, col: 9 }]
	},
	E9: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 6 }, facing: 'S' },
			{ class: 'BB', bow: { row: 5, col: 3 }, facing: 'N' },
			{ class: 'DD', bow: { row: 3, col: 12 }, facing: 'E' },
			{ class: 'DE', bow: { row: 1, col: 3 }, facing: 'N' },
			{ class: 'PB', bow: { row: 2, col: 0 }, facing: 'W' }
		],
		aircraft: [{ row: 6, col: 6 }, { row: 9, col: 6 }]
	},
	E10: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 3 }, facing: 'S' },
			{ class: 'BB', bow: { row: 6, col: 6 }, facing: 'S' },
			{ class: 'DD', bow: { row: 7, col: 11 }, facing: 'E' },
			{ class: 'DE', bow: { row: 5, col: 11 }, facing: 'E' },
			{ class: 'PB', bow: { row: 4, col: 1 }, facing: 'N' }
		],
		aircraft: [{ row: 6, col: 3 }, { row: 8, col: 3 }]
	},
	F1: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 1 }, facing: 'S' },
			{ class: 'BB', bow: { row: 1, col: 1 }, facing: 'N' },
			{ class: 'DD', bow: { row: 8, col: 4 }, facing: 'W' },
			{ class: 'DE', bow: { row: 0, col: 4 }, facing: 'N' },
			{ class: 'PB', bow: { row: 6, col: 7 }, facing: 'W' }
		],
		aircraft: [{ row: 6, col: 1 }, { row: 8, col: 1 }]
	},
	F2: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 13 }, facing: 'N' },
			{ class: 'BB', bow: { row: 0, col: 5 }, facing: 'N' },
			{ class: 'DD', bow: { row: 0, col: 3 }, facing: 'N' },
			{ class: 'DE', bow: { row: 6, col: 5 }, facing: 'E' },
			{ class: 'PB', bow: { row: 3, col: 8 }, facing: 'W' }
		],
		aircraft: [{ row: 1, col: 13 }, { row: 5, col: 13 }]
	},
	F3: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 5 }, facing: 'W' },
			{ class: 'BB', bow: { row: 5, col: 2 }, facing: 'W' },
			{ class: 'DD', bow: { row: 3, col: 8 }, facing: 'W' },
			{ class: 'DE', bow: { row: 9, col: 0 }, facing: 'S' },
			{ class: 'PB', bow: { row: 2, col: 7 }, facing: 'S' }
		],
		aircraft: [{ row: 7, col: 7 }, { row: 7, col: 8 }]
	},
	F4: {
		ships: [
			{ class: 'CV', bow: { row: 0, col: 0 }, facing: 'N' },
			{ class: 'BB', bow: { row: 8, col: 10 }, facing: 'W' },
			{ class: 'DD', bow: { row: 4, col: 2 }, facing: 'W' },
			{ class: 'DE', bow: { row: 0, col: 7 }, facing: 'N' },
			{ class: 'PB', bow: { row: 6, col: 5 }, facing: 'E' }
		],
		aircraft: [{ row: 1, col: 0 }, { row: 2, col: 0 }]
	},
	F5: {
		ships: [
			{ class: 'CV', bow: { row: 5, col: 8 }, facing: 'W' },
			{ class: 'BB', bow: { row: 7, col: 3 }, facing: 'E' },
			{ class: 'DD', bow: { row: 1, col: 2 }, facing: 'N' },
			{ class: 'DE', bow: { row: 2, col: 4 }, facing: 'N' },
			{ class: 'PB', bow: { row: 8, col: 5 }, facing: 'N' }
		],
		aircraft: [{ row: 5, col: 11 }, { row: 5, col: 12 }]
	},
	F6: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 5 }, facing: 'N' },
			{ class: 'BB', bow: { row: 6, col: 5 }, facing: 'N' },
			{ class: 'DD', bow: { row: 2, col: 0 }, facing: 'N' },
			{ class: 'DE', bow: { row: 6, col: 2 }, facing: 'S' },
			{ class: 'PB', bow: { row: 3, col: 10 }, facing: 'N' }
		],
		aircraft: [{ row: 4, col: 5 }, { row: 5, col: 5 }]
	},
	F7: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 6 }, facing: 'W' },
			{ class: 'BB', bow: { row: 8, col: 2 }, facing: 'W' },
			{ class: 'DD', bow: { row: 4, col: 8 }, facing: 'S' },
			{ class: 'DE', bow: { row: 6, col: 3 }, facing: 'E' },
			{ class: 'PB', bow: { row: 5, col: 4 }, facing: 'S' }
		],
		aircraft: [{ row: 9, col: 8 }, { row: 9, col: 10 }]
	},
	F8: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 8 }, facing: 'N' },
			{ class: 'BB', bow: { row: 3, col: 10 }, facing: 'N' },
			{ class: 'DD', bow: { row: 7, col: 7 }, facing: 'N' },
			{ class: 'DE', bow: { row: 0, col: 6 }, facing: 'N' },
			{ class: 'PB', bow: { row: 3, col: 2 }, facing: 'W' }
		],
		aircraft: [{ row: 1, col: 8 }, { row: 4, col: 8 }]
	},
	F9: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 7 }, facing: 'E' },
			{ class: 'BB', bow: { row: 5, col: 0 }, facing: 'W' },
			{ class: 'DD', bow: { row: 7, col: 12 }, facing: 'S' },
			{ class: 'DE', bow: { row: 6, col: 6 }, facing: 'E' },
			{ class: 'PB', bow: { row: 2, col: 0 }, facing: 'W' }
		],
		aircraft: [{ row: 1, col: 4 }, { row: 1, col: 7 }]
	},
	F10: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 13 }, facing: 'N' },
			{ class: 'BB', bow: { row: 6, col: 6 }, facing: 'E' },
			{ class: 'DD', bow: { row: 3, col: 4 }, facing: 'E' },
			{ class: 'DE', bow: { row: 9, col: 12 }, facing: 'S' },
			{ class: 'PB', bow: { row: 1, col: 5 }, facing: 'W' }
		],
		aircraft: [{ row: 3, col: 13 }, { row: 5, col: 13 }]
	},
	G1: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 4 }, facing: 'E' },
			{ class: 'BB', bow: { row: 6, col: 2 }, facing: 'S' },
			{ class: 'DD', bow: { row: 3, col: 3 }, facing: 'W' },
			{ class: 'DE', bow: { row: 7, col: 4 }, facing: 'W' },
			{ class: 'PB', bow: { row: 7, col: 13 }, facing: 'N' }
		],
		aircraft: [{ row: 9, col: 1 }, { row: 9, col: 3 }]
	},
	G2: {
		ships: [
			{ class: 'CV', bow: { row: 2, col: 10 }, facing: 'N' },
			{ class: 'BB', bow: { row: 9, col: 6 }, facing: 'W' },
			{ class: 'DD', bow: { row: 2, col: 3 }, facing: 'N' },
			{ class: 'DE', bow: { row: 5, col: 2 }, facing: 'N' },
			{ class: 'PB', bow: { row: 0, col: 7 }, facing: 'E' }
		],
		aircraft: [{ row: 2, col: 10 }, { row: 6, col: 10 }]
	},
	G3: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 12 }, facing: 'E' },
			{ class: 'BB', bow: { row: 7, col: 6 }, facing: 'E' },
			{ class: 'DD', bow: { row: 7, col: 13 }, facing: 'S' },
			{ class: 'DE', bow: { row: 6, col: 11 }, facing: 'S' },
			{ class: 'PB', bow: { row: 1, col: 11 }, facing: 'E' }
		],
		aircraft: [{ row: 8, col: 10 }, { row: 8, col: 11 }]
	},
	G4: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 4 }, facing: 'E' },
			{ class: 'BB', bow: { row: 3, col: 5 }, facing: 'N' },
			{ class: 'DD', bow: { row: 7, col: 5 }, facing: 'E' },
			{ class: 'DE', bow: { row: 3, col: 0 }, facing: 'S' },
			{ class: 'PB', bow: { row: 0, col: 2 }, facing: 'E' }
		],
		aircraft: [{ row: 9, col: 1 }, { row: 9, col: 2 }]
	},
	G5: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 3 }, facing: 'N' },
			{ class: 'BB', bow: { row: 3, col: 8 }, facing: 'E' },
			{ class: 'DD', bow: { row: 3, col: 1 }, facing: 'N' },
			{ class: 'DE', bow: { row: 1, col: 9 }, facing: 'E' },
			{ class: 'PB', bow: { row: 8, col: 2 }, facing: 'N' }
		],
		aircraft: [{ row: 6, col: 3 }, { row: 7, col: 3 }]
	},
	G6: {
		ships: [
			{ class: 'CV', bow: { row: 5, col: 6 }, facing: 'N' },
			{ class: 'BB', bow: { row: 2, col: 3 }, facing: 'N' },
			{ class: 'DD', bow: { row: 1, col: 6 }, facing: 'N' },
			{ class: 'DE', bow: { row: 9, col: 4 }, facing: 'S' },
			{ class: 'PB', bow: { row: 3, col: 9 }, facing: 'E' }
		],
		aircraft: [{ row: 5, col: 6 }, { row: 6, col: 6 }]
	},
	G7: {
		ships: [
			{ class: 'CV', bow: { row: 5, col: 4 }, facing: 'W' },
			{ class: 'BB', bow: { row: 3, col: 0 }, facing: 'S' },
			{ class: 'DD', bow: { row: 9, col: 2 }, facing: 'W' },
			{ class: 'DE', bow: { row: 4, col: 10 }, facing: 'W' },
			{ class: 'PB', bow: { row: 7, col: 1 }, facing: 'E' }
		],
		aircraft: [{ row: 5, col: 4 }, { row: 5, col: 6 }]
	},
	G8: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 12 }, facing: 'E' },
			{ class: 'BB', bow: { row: 6, col: 2 }, facing: 'N' },
			{ class: 'DD', bow: { row: 4, col: 11 }, facing: 'N' },
			{ class: 'DE', bow: { row: 2, col: 6 }, facing: 'W' },
			{ class: 'PB', bow: { row: 9, col: 4 }, facing: 'W' }
		],
		aircraft: [{ row: 8, col: 8 }, { row: 8, col: 11 }]
	},
	G9: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 2 }, facing: 'S' },
			{ class: 'BB', bow: { row: 0, col: 3 }, facing: 'E' },
			{ class: 'DD', bow: { row: 7, col: 4 }, facing: 'W' },
			{ class: 'DE', bow: { row: 2, col: 3 }, facing: 'E' },
			{ class: 'PB', bow: { row: 8, col: 7 }, facing: 'E' }
		],
		aircraft: [{ row: 5, col: 2 }, { row: 8, col: 2 }]
	},
	G10: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 9 }, facing: 'W' },
			{ class: 'BB', bow: { row: 4, col: 1 }, facing: 'W' },
			{ class: 'DD', bow: { row: 5, col: 4 }, facing: 'W' },
			{ class: 'DE', bow: { row: 8, col: 2 }, facing: 'S' },
			{ class: 'PB', bow: { row: 2, col: 2 }, facing: 'W' }
		],
		aircraft: [{ row: 8, col: 11 }, { row: 8, col: 13 }]
	},
	H1: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 13 }, facing: 'S' },
			{ class: 'BB', bow: { row: 3, col: 8 }, facing: 'N' },
			{ class: 'DD', bow: { row: 5, col: 6 }, facing: 'E' },
			{ class: 'DE', bow: { row: 1, col: 2 }, facing: 'N' },
			{ class: 'PB', bow: { row: 9, col: 10 }, facing: 'W' }
		],
		aircraft: [{ row: 6, col: 13 }, { row: 8, col: 13 }]
	},
	H2: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 6 }, facing: 'N' },
			{ class: 'BB', bow: { row: 0, col: 5 }, facing: 'E' },
			{ class: 'DD', bow: { row: 8, col: 2 }, facing: 'E' },
			{ class: 'DE', bow: { row: 5, col: 2 }, facing: 'E' },
			{ class: 'PB', bow: { row: 4, col: 13 }, facing: 'E' }
		],
		aircraft: [{ row: 3, col: 6 }, { row: 7, col: 6 }]
	},
	H3: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 3 }, facing: 'N' },
			{ class: 'BB', bow: { row: 2, col: 8 }, facing: 'W' },
			{ class: 'DD', bow: { row: 7, col: 5 }, facing: 'S' },
			{ class: 'DE', bow: { row: 8, col: 7 }, facing: 'W' },
			{ class: 'PB', bow: { row: 8, col: 1 }, facing: 'W' }
		],
		aircraft: [{ row: 3, col: 3 }, { row: 4, col: 3 }]
	},
	H4: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 5 }, facing: 'S' },
			{ class: 'BB', bow: { row: 4, col: 7 }, facing: 'W' },
			{ class: 'DD', bow: { row: 1, col: 3 }, facing: 'W' },
			{ class: 'DE', bow: { row: 8, col: 9 }, facing: 'E' },
			{ class: 'PB', bow: { row: 4, col: 3 }, facing: 'S' }
		],
		aircraft: [{ row: 6, col: 5 }, { row: 7, col: 5 }]
	},
	H5: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 3 }, facing: 'S' },
			{ class: 'BB', bow: { row: 3, col: 7 }, facing: 'E' },
			{ class: 'DD', bow: { row: 2, col: 3 }, facing: 'W' },
			{ class: 'DE', bow: { row: 5, col: 6 }, facing: 'N' },
			{ class: 'PB', bow: { row: 2, col: 13 }, facing: 'N' }
		],
		aircraft: [{ row: 8, col: 3 }, { row: 9, col: 3 }]
	},
	H6: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 11 }, facing: 'E' },
			{ class: 'BB', bow: { row: 9, col: 1 }, facing: 'W' },
			{ class: 'DD', bow: { row: 3, col: 5 }, facing: 'W' },
			{ class: 'DE', bow: { row: 6, col: 7 }, facing: 'W' },
			{ class: 'PB', bow: { row: 5, col: 5 }, facing: 'N' }
		],
		aircraft: [{ row: 9, col: 7 }, { row: 9, col: 8 }]
	},
	H7: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 10 }, facing: 'S' },
			{ class: 'BB', bow: { row: 9, col: 8 }, facing: 'S' },
			{ class: 'DD', bow: { row: 0, col: 6 }, facing: 'N' },
			{ class: 'DE', bow: { row: 4, col: 3 }, facing: 'E' },
			{ class: 'PB', bow: { row: 8, col: 3 }, facing: 'S' }
		],
		aircraft: [{ row: 4, col: 10 }, { row: 6, col: 10 }]
	},
	H8: {
		ships: [
			{ class: 'CV', bow: { row: 0, col: 8 }, facing: 'W' },
			{ class: 'BB', bow: { row: 0, col: 1 }, facing: 'N' },
			{ class: 'DD', bow: { row: 4, col: 5 }, facing: 'W' },
			{ class: 'DE', bow: { row: 7, col: 7 }, facing: 'S' },
			{ class: 'PB', bow: { row: 7, col: 9 }, facing: 'S' }
		],
		aircraft: [{ row: 0, col: 8 }, { row: 0, col: 11 }]
	},
	H9: {
		ships: [
			{ class: 'CV', bow: { row: 5, col: 6 }, facing: 'S' },
			{ class: 'BB', bow: { row: 0, col: 8 }, facing: 'N' },
			{ class: 'DD', bow: { row: 8, col: 1 }, facing: 'W' },
			{ class: 'DE', bow: { row: 3, col: 9 }, facing: 'N' },
			{ class: 'PB', bow: { row: 0, col: 0 }, facing: 'W' }
		],
		aircraft: [{ row: 2, col: 6 }, { row: 5, col: 6 }]
	},
	H10: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 3 }, facing: 'N' },
			{ class: 'BB', bow: { row: 6, col: 5 }, facing: 'N' },
			{ class: 'DD', bow: { row: 3, col: 12 }, facing: 'N' },
			{ class: 'DE', bow: { row: 1, col: 10 }, facing: 'N' },
			{ class: 'PB', bow: { row: 1, col: 13 }, facing: 'E' }
		],
		aircraft: [{ row: 5, col: 3 }, { row: 7, col: 3 }]
	},
	I1: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 4 }, facing: 'W' },
			{ class: 'BB', bow: { row: 4, col: 2 }, facing: 'N' },
			{ class: 'DD', bow: { row: 4, col: 4 }, facing: 'S' },
			{ class: 'DE', bow: { row: 4, col: 11 }, facing: 'W' },
			{ class: 'PB', bow: { row: 9, col: 3 }, facing: 'W' }
		],
		aircraft: [{ row: 7, col: 5 }, { row: 7, col: 7 }]
	},
	I2: {
		ships: [
			{ class: 'CV', bow: { row: 9, col: 0 }, facing: 'W' },
			{ class: 'BB', bow: { row: 7, col: 7 }, facing: 'E' },
			{ class: 'DD', bow: { row: 6, col: 13 }, facing: 'N' },
			{ class: 'DE', bow: { row: 3, col: 1 }, facing: 'N' },
			{ class: 'PB', bow: { row: 4, col: 11 }, facing: 'W' }
		],
		aircraft: [{ row: 9, col: 0 }, { row: 9, col: 4 }]
	},
	I3: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 7 }, facing: 'W' },
			{ class: 'BB', bow: { row: 4, col: 13 }, facing: 'S' },
			{ class: 'DD', bow: { row: 5, col: 0 }, facing: 'W' },
			{ class: 'DE', bow: { row: 4, col: 5 }, facing: 'W' },
			{ class: 'PB', bow: { row: 7, col: 13 }, facing: 'N' }
		],
		aircraft: [{ row: 8, col: 9 }, { row: 8, col: 10 }]
	},
	I4: {
		ships: [
			{ class: 'CV', bow: { row: 2, col: 9 }, facing: 'E' },
			{ class: 'BB', bow: { row: 5, col: 8 }, facing: 'N' },
			{ class: 'DD', bow: { row: 8, col: 7 }, facing: 'E' },
			{ class: 'DE', bow: { row: 5, col: 13 }, facing: 'N' },
			{ class: 'PB', bow: { row: 2, col: 3 }, facing: 'S' }
		],
		aircraft: [{ row: 2, col: 6 }, { row: 2, col: 7 }]
	},
	I5: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 10 }, facing: 'E' },
			{ class: 'BB', bow: { row: 2, col: 1 }, facing: 'W' },
			{ class: 'DD', bow: { row: 7, col: 4 }, facing: 'S' },
			{ class: 'DE', bow: { row: 8, col: 4 }, facing: 'W' },
			{ class: 'PB', bow: { row: 6, col: 6 }, facing: 'N' }
		],
		aircraft: [{ row: 4, col: 9 }, { row: 4, col: 10 }]
	},
	I6: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 2 }, facing: 'S' },
			{ class: 'BB', bow: { row: 5, col: 7 }, facing: 'N' },
			{ class: 'DD', bow: { row: 6, col: 13 }, facing: 'N' },
			{ class: 'DE', bow: { row: 9, col: 5 }, facing: 'S' },
			{ class: 'PB', bow: { row: 2, col: 7 }, facing: 'N' }
		],
		aircraft: [{ row: 4, col: 2 }, { row: 5, col: 2 }]
	},
	I7: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 11 }, facing: 'E' },
			{ class: 'BB', bow: { row: 0, col: 3 }, facing: 'W' },
			{ class: 'DD', bow: { row: 8, col: 3 }, facing: 'W' },
			{ class: 'DE', bow: { row: 9, col: 7 }, facing: 'E' },
			{ class: 'PB', bow: { row: 6, col: 13 }, facing: 'S' }
		],
		aircraft: [{ row: 7, col: 7 }, { row: 7, col: 9 }]
	},
	I8: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 8 }, facing: 'E' },
			{ class: 'BB', bow: { row: 5, col: 9 }, facing: 'W' },
			{ class: 'DD', bow: { row: 1, col: 5 }, facing: 'W' },
			{ class: 'DE', bow: { row: 7, col: 2 }, facing: 'S' },
			{ class: 'PB', bow: { row: 3, col: 0 }, facing: 'W' }
		],
		aircraft: [{ row: 8, col: 4 }, { row: 8, col: 7 }]
	},
	I9: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 4 }, facing: 'W' },
			{ class: 'BB', bow: { row: 9, col: 2 }, facing: 'S' },
			{ class: 'DD', bow: { row: 7, col: 9 }, facing: 'S' },
			{ class: 'DE', bow: { row: 4, col: 4 }, facing: 'N' },
			{ class: 'PB', bow: { row: 0, col: 3 }, facing: 'N' }
		],
		aircraft: [{ row: 8, col: 4 }, { row: 8, col: 7 }]
	},
	I10: {
		ships: [
			{ class: 'CV', bow: { row: 0, col: 5 }, facing: 'W' },
			{ class: 'BB', bow: { row: 2, col: 12 }, facing: 'E' },
			{ class: 'DD', bow: { row: 7, col: 11 }, facing: 'W' },
			{ class: 'DE', bow: { row: 5, col: 13 }, facing: 'E' },
			{ class: 'PB', bow: { row: 4, col: 8 }, facing: 'E' }
		],
		aircraft: [{ row: 0, col: 7 }, { row: 0, col: 9 }]
	},
	J1: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 13 }, facing: 'S' },
			{ class: 'BB', bow: { row: 6, col: 11 }, facing: 'N' },
			{ class: 'DD', bow: { row: 6, col: 3 }, facing: 'N' },
			{ class: 'DE', bow: { row: 3, col: 4 }, facing: 'E' },
			{ class: 'PB', bow: { row: 7, col: 5 }, facing: 'W' }
		],
		aircraft: [{ row: 4, col: 13 }, { row: 6, col: 13 }]
	},
	J2: {
		ships: [
			{ class: 'CV', bow: { row: 2, col: 4 }, facing: 'N' },
			{ class: 'BB', bow: { row: 0, col: 8 }, facing: 'E' },
			{ class: 'DD', bow: { row: 1, col: 8 }, facing: 'N' },
			{ class: 'DE', bow: { row: 7, col: 6 }, facing: 'E' },
			{ class: 'PB', bow: { row: 9, col: 10 }, facing: 'W' }
		],
		aircraft: [{ row: 2, col: 4 }, { row: 6, col: 4 }]
	},
	J3: {
		ships: [
			{ class: 'CV', bow: { row: 7, col: 0 }, facing: 'W' },
			{ class: 'BB', bow: { row: 2, col: 6 }, facing: 'N' },
			{ class: 'DD', bow: { row: 0, col: 13 }, facing: 'N' },
			{ class: 'DE', bow: { row: 5, col: 12 }, facing: 'S' },
			{ class: 'PB', bow: { row: 4, col: 1 }, facing: 'S' }
		],
		aircraft: [{ row: 7, col: 2 }, { row: 7, col: 3 }]
	},
	J4: {
		ships: [
			{ class: 'CV', bow: { row: 1, col: 0 }, facing: 'N' },
			{ class: 'BB', bow: { row: 9, col: 0 }, facing: 'S' },
			{ class: 'DD', bow: { row: 1, col: 9 }, facing: 'W' },
			{ class: 'DE', bow: { row: 4, col: 7 }, facing: 'E' },
			{ class: 'PB', bow: { row: 0, col: 3 }, facing: 'N' }
		],
		aircraft: [{ row: 3, col: 0 }, { row: 4, col: 0 }]
	},
	J5: {
		ships: [
			{ class: 'CV', bow: { row: 5, col: 3 }, facing: 'S' },
			{ class: 'BB', bow: { row: 1, col: 11 }, facing: 'E' },
			{ class: 'DD', bow: { row: 9, col: 8 }, facing: 'E' },
			{ class: 'DE', bow: { row: 4, col: 11 }, facing: 'W' },
			{ class: 'PB', bow: { row: 3, col: 0 }, facing: 'S' }
		],
		aircraft: [{ row: 4, col: 3 }, { row: 5, col: 3 }]
	},
	J6: {
		ships: [
			{ class: 'CV', bow: { row: 8, col: 11 }, facing: 'E' },
			{ class: 'BB', bow: { row: 2, col: 3 }, facing: 'W' },
			{ class: 'DD', bow: { row: 4, col: 10 }, facing: 'S' },
			{ class: 'DE', bow: { row: 0, col: 13 }, facing: 'N' },
			{ class: 'PB', bow: { row: 9, col: 3 }, facing: 'E' }
		],
		aircraft: [{ row: 8, col: 7 }, { row: 8, col: 8 }]
	},
	J7: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 6 }, facing: 'W' },
			{ class: 'BB', bow: { row: 7, col: 3 }, facing: 'W' },
			{ class: 'DD', bow: { row: 0, col: 7 }, facing: 'N' },
			{ class: 'DE', bow: { row: 8, col: 12 }, facing: 'E' },
			{ class: 'PB', bow: { row: 5, col: 2 }, facing: 'S' }
		],
		aircraft: [{ row: 4, col: 6 }, { row: 4, col: 8 }]
	},
	J8: {
		ships: [
			{ class: 'CV', bow: { row: 3, col: 1 }, facing: 'N' },
			{ class: 'BB', bow: { row: 3, col: 12 }, facing: 'S' },
			{ class: 'DD', bow: { row: 6, col: 10 }, facing: 'S' },
			{ class: 'DE', bow: { row: 9, col: 7 }, facing: 'S' },
			{ class: 'PB', bow: { row: 0, col: 4 }, facing: 'N' }
		],
		aircraft: [{ row: 3, col: 1 }, { row: 6, col: 1 }]
	},
	J9: {
		ships: [
			{ class: 'CV', bow: { row: 0, col: 6 }, facing: 'W' },
			{ class: 'BB', bow: { row: 4, col: 12 }, facing: 'N' },
			{ class: 'DD', bow: { row: 3, col: 2 }, facing: 'N' },
			{ class: 'DE', bow: { row: 9, col: 4 }, facing: 'S' },
			{ class: 'PB', bow: { row: 1, col: 2 }, facing: 'S' }
		],
		aircraft: [{ row: 0, col: 7 }, { row: 0, col: 10 }]
	},
	J10: {
		ships: [
			{ class: 'CV', bow: { row: 4, col: 4 }, facing: 'W' },
			{ class: 'BB', bow: { row: 1, col: 8 }, facing: 'W' },
			{ class: 'DD', bow: { row: 3, col: 0 }, facing: 'N' },
			{ class: 'DE', bow: { row: 3, col: 2 }, facing: 'S' },
			{ class: 'PB', bow: { row: 8, col: 2 }, facing: 'N' }
		],
		aircraft: [{ row: 4, col: 6 }, { row: 4, col: 8 }]
	}
} as const satisfies Record<string, Formation>;

export const FORMATION_IDS = Object.keys(FORMATIONS) as FormationId[];
